name: Build IPTV Playlist

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */2 * * *"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Download IPTV sources
        run: |
          mkdir -p data
          curl -L https://iptv-org.github.io/iptv/index.m3u -o data/global1.m3u
          echo "#EXTM3U" > playlist_fixed.m3u
          grep -h -v '^#EXTM3U' data/*.m3u | awk '!seen[$0]++' >> playlist_fixed.m3u

      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add playlist_fixed.m3u || true
          git commit -m "Update playlist" || true
          git push
